/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PostnHire;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ADMIN
 */
public class PostJob2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form PostJob2
     */
    public PostJob2() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI user = (BasicInternalFrameUI)this.getUI();
        user.setNorthPane(null);
        initComponents();
        this.setSize(564, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LjobApp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tjobtitle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tcompanyname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Tlocation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Tskills = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CBjobtype = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAjobdesc = new javax.swing.JTextArea();
        Bviewjobs = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(203, 178, 107));
        jPanel1.setPreferredSize(new java.awt.Dimension(532, 481));

        LjobApp.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        LjobApp.setForeground(new java.awt.Color(59, 59, 156));
        LjobApp.setText("\"Post your job and reach thousands in seconds!\"");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(59, 59, 156));
        jLabel5.setText("Job Title:");

        Tjobtitle.setBackground(new java.awt.Color(153, 255, 255));
        Tjobtitle.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(59, 59, 156));
        jLabel6.setText("Company name:");

        Tcompanyname.setBackground(new java.awt.Color(153, 255, 255));
        Tcompanyname.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(59, 59, 156));
        jLabel7.setText("Location:");

        Tlocation.setBackground(new java.awt.Color(153, 255, 255));
        Tlocation.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(59, 59, 156));
        jLabel8.setText("Skills Required:");

        Tskills.setBackground(new java.awt.Color(153, 255, 255));
        Tskills.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(59, 59, 156));
        jLabel11.setText("Select Job Type:");

        CBjobtype.setBackground(new java.awt.Color(153, 255, 255));
        CBjobtype.setForeground(new java.awt.Color(0, 0, 0));
        CBjobtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full Time", "Part-Time", "Freelance", "Contract/Temporary" }));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(59, 59, 156));
        jLabel12.setText("Job Description:");

        TAjobdesc.setBackground(new java.awt.Color(153, 255, 255));
        TAjobdesc.setColumns(20);
        TAjobdesc.setForeground(new java.awt.Color(0, 0, 0));
        TAjobdesc.setRows(5);
        jScrollPane1.setViewportView(TAjobdesc);

        Bviewjobs.setBackground(new java.awt.Color(59, 59, 156));
        Bviewjobs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bviewjobs.setForeground(new java.awt.Color(203, 178, 107));
        Bviewjobs.setText("Post Job");
        Bviewjobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BviewjobsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBjobtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Tcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tjobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tskills, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(Bviewjobs, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LjobApp)
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LjobApp)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Tjobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Tlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tskills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBjobtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(Bviewjobs, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BviewjobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BviewjobsMouseClicked
        String jobTitle = Tjobtitle.getText().trim();
        String company = Tcompanyname.getText().trim();
        String location = Tlocation.getText().trim();
        String skill = Tskills.getText().trim();
        String type = CBjobtype.getSelectedItem().toString();
        String jobDesc = TAjobdesc.getText().trim();

        //if walay sulod and textarea
        if (jobTitle.isEmpty() || jobDesc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "please fill in the details");
        }

        String jobs = "C:\\Users\\ADMIN\\Documents\\PostnHire\\jobs.txt";
        File jobfile = new File(jobs);

        try (FileWriter data = new FileWriter(jobfile, true)) {
            data.write("========== Job Post ==========\n");
            data.write("Title:          " + jobTitle + "\n");
            data.write("Company Name:   " + company + "\n");
            data.write("Location:       " + location + "\n");
            data.write("Skill Required: " + skill + "\n");
            data.write("Job Type:       " + type + "\n");                                 
            data.write("description:    " + jobDesc + "\n");
            data.write("--------------------------------------------------------------\n");
            data.write(" ");

            JOptionPane.showMessageDialog(this, "Job Posted");
            Tjobtitle.setText("");
            Tcompanyname.setText(" ");
            Tlocation.setText(" ");
            Tskills.setText(" ");
            CBjobtype.setSelectedIndex(0);
            TAjobdesc.setText("");

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving job");
        }

    }//GEN-LAST:event_BviewjobsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bviewjobs;
    private javax.swing.JComboBox<String> CBjobtype;
    private javax.swing.JLabel LjobApp;
    private javax.swing.JTextArea TAjobdesc;
    private javax.swing.JTextField Tcompanyname;
    private javax.swing.JTextField Tjobtitle;
    private javax.swing.JTextField Tlocation;
    private javax.swing.JTextField Tskills;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
